# Generated by Django 2.0 on 2017-12-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupBuyApp', '0005_auto_20171207_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='hasMax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountlot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupBuyApp.Account'),
        ),
        migrations.AddField(
            model_name='accountlot',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupBuyApp.Lot'),
        ),
    ]
