# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupBuyApp', '0006_account_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='hasMax',
            field=models.BooleanField(default=False),
        ),
    ]
