# Generated by Django 2.0 on 2017-12-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupBuyApp', '0006_auto_20171219_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
